[package]
name = "qqq-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
qqq-domain.workspace = true
qqq-engine.workspace = true
eframe.workspace = true
egui_plot.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
